name = "backend"
main = "src/index.ts"
compatibility_date = "2024-11-05"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
#prisma pool connection
#pick up from environment varibles
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMmNmZjk1YmEtNjYwNC00NmFlLWJmNTYtOGUzYjE4ZGU4MTk4IiwidGVuYW50X2lkIjoiYzk0ODI3NjhkYjdjMzc4Yzk3NzM2NTFlNzhlOTI5MDIxMjNiMzYxMjQ3NjRlZTBmYTYwOWUxNzA5ZTliMWFhYyIsImludGVybmFsX3NlY3JldCI6IjgxMjM5NzhiLTdmMmItNDliNy04NmNjLWNjMDljYmVlYTgzMyJ9.d2DIp1gdJIpvCEnwn3W1NqfLNt5SlD-a_PFlTO5eHZk"
JWT_SECRET="prod_jwt_secret@123"

